DB_SIZE = 100
TABLE_NAMES = [
    'TRADE_DATE_LIST_DAILY',
    'TRADE_DATE_LIST_WEEKLY',
    'TRADE_DATE_LIST_MONTHLY',
    'SH_STOCK_LIST',
    'SZ_STOCK_LIST',
    'SH_INDEX_DAILY',
    'SH_INDEX_WEEKLY',
    'SH_INDEX_MONTHLY',
    'SH_DETAILS_DAILY',
    'SH_DETAILS_WEEKLY',
    'SH_DETAILS_MONTHLY',
    'SH_LIMITS_STATISTIC_DETAILS',
    'SZ_INDEX_DAILY',
    'SZ_INDEX_WEEKLY',
    'SZ_INDEX_MONTHLY',
    'SZ_DETAILS_DAILY',
    'SZ_DETAILS_WEEKLY',
    'SZ_DETAILS_MONTHLY',
    'SZ_LIMITS_STATISTIC_DETAILS',
]

CREATION_SQL = []